service: lambda-stock

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  handler:
    handler: handler.handler
    events:
      - httpApi:
          path: /
          method: get